joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan
    joint_speed: 1.0
    motor:
        id: 10
        init: 0
        min: 200
        max: 823
        
joint5_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt
    joint_speed: 1.0
    motor:
        id: 11
        init: 0
        min: 350
        max: 680
